name: Build Swift Framework

on:
  push:
    branches: release

jobs:
  release:
    runs-on: macos-latest
    env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    steps:
    - name: Checkout framework repository
      uses: actions/checkout@v2
      with:
        path: framework
        fetch-depth: 0

    - name: Bump version
      id: increment_version
      working-directory: framework
      run: echo "::set-output name=next-version::$(git describe --tags $(git rev-list --tags --max-count=1) | awk -F. -v OFS=. '{$NF++;print}')"

    - name: Update library version
      run: sed -ie '/let sdkVersion:\ String/s/.*/    let sdkVersion:\ String = \"iOS_handset_${{ steps.increment_version.outputs.next-version }}\";/' HandsetAssistant/HandsetRecorder.swift
      working-directory: framework

    - name: Build Framework
      working-directory: framework
      run: ./build_framework.sh

    - name: Checkout package repository
      uses: actions/checkout@v2
      with:
        repository: 'huq-industries/handset-assistant-ios'
        token: ${{ secrets.HUQMACHINE_TOKEN }}
        path: package
        fetch-depth: 0

    - name: Delete old framework
      working-directory: package
      run: rm -rf Sources/HandsetAssistant/Framework/HandsetAssistant.xcframework

    - name: Copy new framework
      run: cp -r framework/build/HandsetAssistant.xcframework package/Sources/HandsetAssistant/Framework/

    - name: Update package project
      uses: EndBug/add-and-commit@v9
      with:
        message: Framework binary updated from handset-assistant-ios-framework
        add: Sources/HandsetAssistant/Framework/*
        tag: ${{ steps.increment_version.outputs.next-version }}
        cwd: package
        new_branch: main

    - name: Install podspec bump
      run: npm install -g podspec-bump

    - name: Install CocoaPods gem
      run: sudo gem install cocoapods

    - name: Bump podspec version
      working-directory: framework
      run: podspec-bump -p HandsetAssistant.podspec -i "${{ steps.increment_version.outputs.next-version }}" -w
        
    - name: Update Changelog
      working-directory: framework
      run: sed -i "" -e '6a\'$'\n''## ${{ steps.increment_version.outputs.next-version}}' CHANGELOG.md

    - name: Update framework project
      uses: EndBug/add-and-commit@v9
      with:
        message: Bump version and release
        add: '["CHANGELOG.md", "HandsetAssistant/HandsetRecorder.swift"]'
        tag: ${{ steps.increment_version.outputs.next-version }}
        cwd: framework
        new_branch: main

    - name: Set up pod trunk
      working-directory: framework
      run: pod setup

    - name: Push podspec
      working-directory: framework
      run: pod trunk push HandsetAssistant.podspec
